model:
  base_learning_rate: 1.0e-6
  target: wan.wrapper.trainer.base.Trainer
  params:
    gt_key: image
    image_key: reference
    control_key: pose
    face_key: face
    text_key: text
    mcode_key: motion_code
    ucg_text_rate: 0.1
    ucg_img_rate: 0.1
    ucg_control_rate: 0.
    ucg_face_rate: 0.1
    hf_load: true
    max_reft_len: 13
    scheduler_config:
      scheduler_type: flow
      num_train_timesteps: 1000
      shift: 5.0

    transformer_config:
      ckpt_path: Wan-AI/Wan2.2-Animate-14B
      # ckpt_path: models/chen-lora

    vae_config:
      target: wan.modules.vae.WanVAE
      params:
        vae_pth: pretrained_models/wan2.2/Wan2.1_VAE.pth
#        device: cpu

    img_embedder_config:
      target: wan.modules.embedder.clip.CLIPModel
      params:
#        device: cpu
        checkpoint_path: pretrained_models/wan2.2/models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth

    txt_embedder_config:
      target: wan.modules.embedder.t5.T5EncoderModel
      params:
#        device: cpu
        checkpoint_path: pretrained_models/wan2.2/models_t5_umt5-xxl-enc-bf16.pth
        tokenizer_path: google/umt5-xxl
        text_len: 512


dataloader:
  class: VideoLoader
  params:
    json_key: motion
    anchor_key: video
    pose_key: mesh
    # face_key: face-smpl
#    depth_key: depth
    # lmdb_key: seamless_inter/face-lmdb
    # load_size: [720, 1280]
    # candidate_sizes (high-res): [[720, 1280], [1280, 720], [1024, 1024]]
    candidate_sizes: [[512, 768], [768, 512], [640, 640]]
    frame_length: 81
  shuffle: true


logger:
  log_on_batch_idx: false
  log_first_step: false
  log_gif: true
  log_img_step: 500